# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # environment:
    #   NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    # env_file:
    #   - .env.production
    command: >
      sh -c "yarn build && yarn start"
