services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "yarn build && yarn start"
    restart: unless-stopped
