import FooterBar from "@/components/ui/footerBar";
import Header from "@/components/ui/header";
import Sidebar from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-gray-100`}>
        <div className="flex">
          <Sidebar />
          <div className="flex-1 flex flex-col">
            <Header />
            <main className="flex-1 p-4 ml-16">{children}</main>
            <div className="pt-8">
              <FooterBar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
